# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1326da75f35080a5aa9440f98a4fb7cd"
application_url = "https://planning-fault-invited-roughly.trycloudflare.com"
embedded = true
name = "UpFile - Uploaded File Orders"
handle = "upfile-app"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order"
  filter = "line_items.properties.name:__upfile_id"
  include_fields = [
  "id",
  "customer.id",
  "customer.first_name",
  "customer.last_name",
  "location_id",
  "financial_status",
  "fulfillment_status",
  "current_total_price",
  "created_at",
  "test",
  "note",
  "user_id",
  "tags",
  "note_attributes",
  "total_subtotal",
  "total_discounts",
  "total_price",
  "total_outstanding",
  "order_number",
  "line_items.id",
  "line_items.quantity",
  "line_items.properties",
  "line_items.product_id",
  "line_items.title",
  "line_items.price",
  "line_items.total_discount",
  "line_items.variant_id",
  "line_items.variant_title"
]

[app_proxy]
url = "https://planning-fault-invited-roughly.trycloudflare.com/app/proxy"
subpath = "dropzone"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_order_edits, read_orders, read_themes, unauthenticated_read_checkouts, unauthenticated_read_content, unauthenticated_read_customer_tags, unauthenticated_read_customers, unauthenticated_read_metaobjects, unauthenticated_read_product_inventory, unauthenticated_read_product_listings, unauthenticated_read_product_pickup_locations, unauthenticated_read_product_tags, unauthenticated_read_selling_plans, unauthenticated_write_checkouts, unauthenticated_write_customers, write_app_proxy, write_content, write_metaobjects, write_metaobject_definitions, write_order_edits, write_orders, write_products"

[auth]
redirect_urls = [
  "https://planning-fault-invited-roughly.trycloudflare.com/auth/callback",
  "https://planning-fault-invited-roughly.trycloudflare.com/auth/shopify/callback",
  "https://planning-fault-invited-roughly.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "upfile-demo.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
