# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1326da75f35080a5aa9440f98a4fb7cd"
application_url = "https://reid-years-finland-financing.trycloudflare.com"
embedded = true
name = "File Dropzone Uploader"
handle = "file-dropzone-uploader"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_orders, write_metaobjects, write_content"

[auth]
redirect_urls = [
  "https://reid-years-finland-financing.trycloudflare.com/auth/callback",
  "https://reid-years-finland-financing.trycloudflare.com/auth/shopify/callback",
  "https://reid-years-finland-financing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "custom-component-portfolio.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
