api_version = "2025-01"

[[extensions]]
type = "ui_extension"
name = "Customer Account Order Image"
handle = "customer-account-order-image"

[[extensions.targeting]]
module = "./src/OrderImagesBlock.tsx"
target = "customer-account.order-status.cart-line-item.render-after"



# ! add multiple targets:
# [[extensions.targeting]]
# module = "./src/CustomerAccountExtensionFullPage.tsx"
# target = "customer-account.page.render"